{
  "type": "record",
  "name": "DeliveryEvent",
  "namespace": "br.com.olist.events",
  "fields": [
    {
      "name": "event_id",
      "type": "string"
    },
    {
      "name": "order_id",
      "type": "string"
    },
    {
      "name": "delivery_status",
      "type": {
        "type": "enum",
        "name": "DeliveryStatus",
        "symbols": [
          "PICKED_UP",
          "IN_TRANSIT",
          "OUT_FOR_DELIVERY",
          "DELIVERED"
        ]
      }
    },
    {
      "name": "customer_state",
      "type": "string"
    },
    {
      "name": "latitude",
      "type": "double"
    },
    {
      "name": "longitude",
      "type": "double"
    },
    {
      "name": "event_timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "metadata",
      "type": {
        "type": "record",
        "name": "DeliveryMetadata",
        "fields": [
          {
            "name": "source",
            "type": "string"
          },
          {
            "name": "version",
            "type": "string",
            "default": "1.0"
          },
          {
            "name": "producer_id",
            "type": "string"
          }
        ]
      }
    }
  ]
}
